name: music_vibe
description: "A new Flutter project."

publish_to: "none"

version: 1.1.1+3

environment:
  sdk: ^3.5.0

dependencies:
  android_intent_plus: ^6.0.0
  audio_service: ^0.18.15
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  just_audio: ^0.10.5
  on_audio_query: ^2.9.0
  package_info_plus: ^9.0.0
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.3.2

dependency_overrides:
  on_audio_query_android:
    path: ./local_plugins/on_audio_query_android

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter
  rename: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/icons/logo.png"
  adaptive_icon_background: "assets/icons/logo_background.png"
  adaptive_icon_foreground: "assets/icons/logo_foreground.png"

flutter_native_splash:
  color: "#7C4DFF"
  image: assets/images/splash.png
  color_dark: "#7C4DFF"
  image_dark: assets/images/splash.png
  android_12:
    color: "#7C4DFF"
    image: assets/icons/logo.png
    color_dark: "#7C4DFF"
    image_dark: assets/icons/logo.png

  fullscreen: true
